# Generated by Django 3.0.3 on 2020-03-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200305_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1500),
        ),
    ]
